name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-debug:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install gcc make openssl git
    - name: Generate cert debug
      run: sh lotorssl/src/scripts/gen_cert_debug.sh
    - name: Get lotormath
      run: git clone https://github.com/smurfd/lotormath lotorssl/src/lotormath
    - name: Compile
      run: make -Clotorssl/src

  build-latest-debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get -y install gcc make openssl git
    - name: Generate cert debug
      run: sh lotorssl/src/scripts/gen_cert_debug.sh
    - name: Get lotormath
      run: git clone https://github.com/smurfd/lotormath lotorssl/src/lotormath
    - name: Compile
      run: make -Clotorssl/src
